/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci_620_grading_software;

import csci_620_grading_software.RecordUtils.Configuration;

public class App {
    
    public static void main(String[] args) {
	
	Configuration configuration = Utils.readConfigFile();
	AutoGrader grader = null;	
	if (configuration.language().toLowerCase().equals("python")) {
	    grader = new PythonGrader(configuration);
	} else if (configuration.language().toLowerCase().equals("java")) {
	     grader = new JavaGrader(configuration);
	}
	/* Issue issue = new Issue("console.includes('error') && !output.includes('some id')",
			"some text");

	issue.evaluateCondition("error", "no", 0); */

	grader.startGrading();
	
    }
	
}
